=== simobe-git/tesina-main/dtd/domande.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT domande (domanda*)>
<!ELEMENT domanda (codice_gioco, titolo, contenuto, autore, data, risposta*)>
<!ELEMENT codice_gioco (#PCDATA)>
<!ELEMENT titolo (#PCDATA)>
<!ELEMENT contenuto (#PCDATA)>
<!ELEMENT autore (#PCDATA)>
<!ELEMENT data (#PCDATA)>
<!ELEMENT risposta (contenuto, autore, data)>
<!ATTLIST risposta id CDATA #REQUIRED>
<!-- <!ELEMENT punteggio (utilita, supporto)>
<!ELEMENT utilita (#PCDATA)>
<!ELEMENT supporto (#PCDATA)>

=== simobe-git/tesina-main/xml/domande.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE domande SYSTEM "../dtd/domande.dtd">
<domande>
  <domanda>
    <codice_gioco>1</codice_gioco>
    <titolo>Consiglio età di gioco</titolo>
    <contenuto>Consigliereste di giocare ad un ragazzo di 13 anni?</contenuto>
    <autore>mario123</autore>
    <data>2024-03-20</data>
    <risposta id="1">
      <contenuto>Nell'età minima viene consigliato almeno 14 anni, per cui direi di aspettare!</contenuto>
      <autore>luigi99</autore>
      <data>2024-03-22</data>
    </risposta>
    <risposta id="2">
      <contenuto>Anche se l'età minima è 14, ci si può tranquillamente giocare prima secondo me.</contenuto>
      <autore>anna22</autore>
      <data>2024-03-23</data>
    </risposta>
    <risposta id="3">
      <contenuto>No, bisogna rispettare l'età!</contenuto>
      <autore>giuseppeee</autore>
      <data>2024-03-29</data>
    </risposta>
    <risposta id="7">
      <contenuto>risposta!</contenuto>
      <autore>cliente1</autore>
      <data>2025-04-16</data>
    </risposta>
    <risposta id="8">
      <contenuto>hs</contenuto>
      <autore>cliente1</autore>
      <data>2025-04-20</data>
    </risposta>
    <risposta id="9">
      <contenuto>risposta pasquetta2</contenuto>
      <autore>cliente1</autore>
      <data>2025-04-21</data>
    </risposta>
    <risposta id="10">
      <contenuto>risposta3 pasquetta</contenuto>
      <autore>cliente1</autore>
      <data>2025-04-21</data>
    </risposta>
  </domanda>
  <domanda>
    <codice_gioco>1</codice_gioco>
    <titolo>Vi è piaciuto il gioco?</titolo>
    <contenuto>Sono indeciso se comprarlo o no: vi è piaciuto? cosa vi ha soddisfatto e cosa non? voglio chiarirmi le idee per decidere se acquistarlo</contenuto>
    <autore>peppe01</autore>
    <data>2024-03-19</data>
    <risposta id="4">
      <contenuto>Secondo me non vale i soldi spesi, vai su altro!</contenuto>
      <autore>luigi99</autore>
      <data>2024-03-21</data>
    </risposta>
    <risposta id="12">
      <contenuto>risposta4 pasquetta</contenuto>
      <autore>cliente1</autore>
      <data>2025-04-21</data>
    </risposta>
  </domanda>
  <domanda>
    <codice_gioco>2</codice_gioco>
    <titolo>Numero di giocatori</titolo>
    <contenuto>Cosa accade se siamo più di 6 giocatori?</contenuto>
    <autore>paolo456</autore>
    <data>2024-03-19</data>
    <risposta id="5">
      <contenuto>Probabilmente i soldi da distribuire a tutti i giocatori non basteranno e, quasi sicuramente, qualche giocatore si troverà pochissime proprietà in suo possesso.</contenuto>
      <autore>anna22</autore>
      <data>2024-03-27</data>
    </risposta>
  </domanda>
  <domanda>
    <codice_gioco>7</codice_gioco>
    <titolo>prova def</titolo>
    <contenuto>prova definitiva, funge?</contenuto>
    <autore>cliente1</autore>
    <data>2025-04-14</data>
    <risposta id="6">
      <contenuto>ora si</contenuto>
      <autore>cliente1</autore>
      <data>2025-04-14</data>
    </risposta>
  </domanda>
  <domanda>
    <codice_gioco>1</codice_gioco>
    <titolo>domanda pasqua</titolo>
    <contenuto>domanda?</contenuto>
    <autore>cliente1</autore>
    <data>2025-04-20</data>
    <risposta id="11">
      <contenuto>risposta3 pasquetta</contenuto>
      <autore>cliente1</autore>
      <data>2025-04-21</data>
    </risposta>
    <risposta id="13">
      <contenuto>risposta5 pasquetta</contenuto>
      <autore>cliente1</autore>
      <data>2025-04-21</data>
    </risposta>
    <risposta id="14">
      <contenuto>risposta6 pasquetta</contenuto>
      <autore>cliente1</autore>
      <data>2025-04-21</data>
    </risposta>
    <risposta id="15">
      <contenuto>risposta7 pasquetta</contenuto>
      <autore>cliente1</autore>
      <data>2025-04-21</data>
    </risposta>
  </domanda>
  <domanda>
    <codice_gioco>9</codice_gioco>
    <titolo>domanda per Cluedo</titolo>
    <contenuto>questa è la domanda per Cluedo. Giusto?</contenuto>
    <autore>cliente1</autore>
    <data>2025-06-05</data>
  </domanda>
  <domanda>
    <codice_gioco>1</codice_gioco>
    <titolo>Prova</titolo>
    <contenuto>Prova prova provaProva prova prova</contenuto>
    <autore>cliente4</autore>
    <data>2025-06-10</data>
    <risposta id="16">
      <contenuto>RISPOSTA PROVA</contenuto>
      <autore>cliente4</autore>
      <data>2025-06-10</data>
    </risposta>
  </domanda>
  <domanda>
    <codice_gioco>11</codice_gioco>
    <titolo>BLABLABLABLA</titolo>
    <contenuto>BLABLA</contenuto>
    <autore>cliente4</autore>
    <data>2025-06-10</data>
    <risposta id="17">
      <contenuto>LALALA</contenuto>
      <autore>cliente1</autore>
      <data>2025-06-10</data>
    </risposta>
  </domanda>
  <domanda>
    <codice_gioco>6</codice_gioco>
    <titolo>PPPPPPPPPP</titolo>
    <contenuto>skcnaclknasncsnak</contenuto>
    <autore>cliente1</autore>
    <data>2025-06-10</data>
    <risposta id="18">
      <contenuto>NSNSNSNNSNS</contenuto>
      <autore>cliente2</autore>
      <data>2025-06-10</data>
    </risposta>
    <risposta id="19">
      <contenuto>&lt;kcsn&lt;ònc&lt;</contenuto>
      <autore>cliente3</autore>
      <data>2025-06-10</data>
    </risposta>
  </domanda>
  <domanda>
    <codice_gioco>6</codice_gioco>
    <titolo>skcnaclknasncsnak</titolo>
    <contenuto>PPPPPPPPPP</contenuto>
    <autore>cliente3</autore>
    <data>2025-06-10</data>
  </domanda>
</domande>
