=== simobe-git/tesina-main/dtd/valuta_recensioni.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT valutazioni (valutazione*)>
<!ELEMENT valutazione (username, id_recensione, stelle)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT id_recensione (#PCDATA)>
<!ELEMENT stelle (#PCDATA)>

=== simobe-git/tesina-main/xml/valuta_recensioni.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE valutazioni SYSTEM "../dtd/valuta_recensioni.dtd">
<valutazioni>
  <valutazione>
    <username>cliente1</username>
    <id_recensione>1</id_recensione>
    <stelle>3</stelle>
  </valutazione>
  <valutazione>
    <username>cliente1</username>
    <id_recensione>2</id_recensione>
    <stelle>5</stelle>
  </valutazione>
  <valutazione>
    <username>cliente1</username>
    <id_recensione>1</id_recensione>
    <stelle>5</stelle>
  </valutazione>
  <valutazione>
    <username>cliente1</username>
    <id_recensione>2</id_recensione>
    <stelle>4</stelle>
  </valutazione>
  <valutazione>
    <username>cliente1</username>
    <id_recensione>2</id_recensione>
    <stelle>2</stelle>
  </valutazione>
</valutazioni>
