=== simobe-git/tesina-main/xsd/pacchetti_crediti.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="pacchetti">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pacchetto" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="codice" type="xs:int"/>
                            <xs:element name="crediti" type="xs:int"/>
                            <xs:element name="prezzo" type="xs:float"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== simobe-git/tesina-main/xml/pacchetti_crediti.xml
<?xml version="1.0" encoding="UTF-8"?>
<pacchetti xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="../xsd/pacchetti_crediti.xsd">

    <pacchetto>
        <codice>1</codice>
        <crediti>30</crediti>
        <prezzo>9.99</prezzo>
    </pacchetto>
    <pacchetto>
        <codice>2</codice>
        <crediti>50</crediti>
        <prezzo>14.99</prezzo>
    </pacchetto>
    <pacchetto>
        <codice>3</codice>
        <crediti>100</crediti>
        <prezzo>25.99</prezzo>
    </pacchetto>
    <pacchetto>
        <codice>4</codice>
        <crediti>200</crediti>
        <prezzo>45.99</prezzo>
    </pacchetto>
</pacchetti>
